name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - minio=7.2.16
  - boto3=1.39.12
  - pandas
  - pip

  - pip:
    - jupyter-ai-cborg @ git+https://github.com/kbaseincubator/cdm-jupyter-ai-cborg.git@v0.1.0
    - jupyterlab_favorites==3.2.2
    - cdm-task-service-client @ git+https://github.com/kbase/cdm-task-service-client.git@0.1.0
    - cdm-spark-manager-client @ git+https://github.com/kbase/cdm-kube-spark-manager-client.git@0.0.1